# Example just get information about the repository whether or not it has
# already been cloned locally.

---
#- hosts	: localhost
- hosts		: pcm1
  gather_facts	: no
#  logfile	: /opt/git/ops.log	

  tasks	:

  - name	: ensure repo is available
    git		: 
      repo	: gith:Autoclimate/Ecommerce-Config.git 
      version	: master 
      accept_hostkey:	True 
      clone	: no
    
  - name  	: Get git stuff
    git		: 
      repo	: gith:Autoclimate/Ecommerce-Config.git
      dest	: /opt/git/checkout/
      clone	: yes 
      update	: yes
      accept_hostkey	: yes
      
#      sudo_user: norm1710

#- name: Get stuff from git
#  git: src=git@github.com:you/your-git-repo.git dest=/opt/git-stuff
#    sudo_user: <your user that has the ssh key>
    
# git://foosball.example.org/path/to/repo.git dest=/srv/checkout clone=no update=no
# git@github.com:Autoclimate/Ecommerce-Config.git
