---
#
# Run: ansible-playbook -sv os_apps_vers.yml -e "hosts=<hostnames/group>"
#
# A role version of playbooks/os_ver.yml
#
# Lists all the variables on a host using a template file os_apps_vers_htm.j2
#

# This template section creates the file (dest:) on the ansible server

# - hosts: localhost
#   gather_facts: False

#  tasks:
- template:
    src: 	os_apps_vers_htm2.j2
    dest: 	/var/www/html/os_apps_vers/index.html
    owner: 'apache'
    group: 'apache'
    mode: 0755
                
#    ignore_errors: True


