---
#
# Run: ansible-playbook -sv ansible-users.yml -e "hosts=<hostnames/group>"
#
# Adds or deletes all users & groups contained in the group_vars/all or group_vars/groupname dirs
# 
# Note that the ssh keys can be picked up from github ;-)

# First we gather facts on the hosts we want

- name: "Add or delete Users and Groups"
  hosts: "{{ hosts }}"
  sudo: True
#  vars_files:
#    - roles/vars/users/test.yml
#    - vars/users/ian_price.yml

  roles:
#    - { role: users_and_groups , users_and_groups: "{{ users_and_groups }}" }
    - { role: ansible-users }
