---
#
# Run: ansible-playbook -sv os_apps_vers.yml -e "hosts=<hostnames/group>"
#
# A role version of playbooks/os_ver.yml
#
# Lists all the variables on a host using a template file
# Outputting to a webpage and file
#

# First we gather facts on the hosts we want

- name: Gather facts from the selected hosts
  hosts: "{{ hosts }}"
  
# Now we run the report creation part
          
- name: Report on the webservers and application code
  hosts: localhost
              
  roles:
    - { role: os_apps_vers, oav_hosts: "{{ hosts }}" }
    
